Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Ferreira de Melo
// Descrição   : Aprendendo variáveis
// Autor(a)    : Ronaldo Capitol
// Data atual  : 29/10/2022
Var
// Seção de Declarações das variáveis 
    primeiroNome, segundoNome, cidade, endereco: caractere
    idade: inteiro

    
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo